---
  - name: restart clamav
    service:
      name: "{{ clamav_daemon }}"
      state: restarted

  - name: restart freshclam
    service:
      name: "{{ freshclam_daemon }}"
      state: restarted